workflows:
  dev-android-release:
    name: Dev Android Release
    max_build_duration: 30
    environment:
      groups:
        - environment_variables
        - keystore_credentials
      flutter: 3.0.5
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Build Release Notes
        script: |
          sh ./scripts/create-release-notes.sh
      - name: Unit Testing
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
          flutter clean
          flutter pub get
          sh ./scripts/create-env.sh
          $FLUTTER_ROOT/bin/dart env.dart
          flutter analyze
          flutter test
      - name: Pre-release scripts
        script: |
          ls -la $FCI_BUILD_DIR
          echo ${CM_KEYSTORE} | base64 --decode > "$FCI_BUILD_DIR/android/app/keystore.jks"
          echo ${CM_KEY_PROPERTIES} | base64 --decode > "$FCI_BUILD_DIR/android/key.properties"
          echo ${CM_FASTLANE_ENV_DEFAULT} | base64 --decode > "$FCI_BUILD_DIR/android/fastlane/.env.default"
      - name: Android Fastlane Release
        script: |
          gem install bundler:1.17.2
          cd android
          bundle install
          bundle exec fastlane release_dev
      - echo "Deployed!"

  production-android-release:
    name: Production Android Release
    max_build_duration: 30
    environment:
      groups:
        - environment_variables
        - keystore_credentials
      flutter: 3.0.5
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: production
          include: true
          source: true
    scripts:
      - name: Build Release Notes
        script: |
          sh ./scripts/create-release-notes.sh
      - name: Unit Testing
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
          flutter clean
          flutter pub get
          sh ./scripts/create-env.sh
          $FLUTTER_ROOT/bin/dart env.dart
          flutter analyze
          flutter test
      - name: Pre-release scripts
        script: |
          ls -la $FCI_BUILD_DIR
          echo ${CM_KEYSTORE} | base64 --decode > "$FCI_BUILD_DIR/android/app/keystore.jks"
          echo ${CM_KEY_PROPERTIES} | base64 --decode > "$FCI_BUILD_DIR/android/key.properties"
          echo ${CM_FASTLANE_ENV_DEFAULT} | base64 --decode > "$FCI_BUILD_DIR/android/fastlane/.env.default"
      - name: Android Fastlane Release
        script: |
          gem install bundler:1.17.2
          cd android
          bundle install
          bundle exec fastlane release_production
      - echo "Deployed!"